// react/3. react-ts/src/components/Game.tsx
import { useState } from 'react';
import '../styles/jing_zi_qi_game.css';

type SquareProp = {
  value: string;
  onSquareClick: () => void;
};

type SquareArr = string[]

// 方格组件
function Square({ value, onSquareClick }: SquareProp) {
  return <button className="square" onClick={onSquareClick}>{value}</button>;
}

function calculateWinner(squareArr: SquareArr) {
  const lineArr = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    [0, 4, 8],
    [2, 4, 6]
  ];
  for (let i = 0; i < lineArr.length; i++) {
    const [a, b, c] = lineArr[i];
    if (squareArr[a] && squareArr[a] === squareArr[b] && squareArr[a] === squareArr[c]) {
      return squareArr[a];
    }
  }
  return null;
}

type BoardProp = {
  xIsNext: boolean;
  squareArr: SquareArr;
  onPlay: (nextSquareArr: SquareArr) => void;
}

// 棋盘组件
function Board({ xIsNext, squareArr, onPlay }: BoardProp) {
  function handleClick(i: number) {
    if (squareArr[i] || calculateWinner(squareArr)) {
      return;
    }
    const nextSquareArr = squareArr.slice();
    if (xIsNext) {
      nextSquareArr[i] = "X";
    } else {
      nextSquareArr[i] = "O";
    }
    onPlay(nextSquareArr);
  }

  const winner = calculateWinner(squareArr);
  let status;
  if (winner) {
    status = `Winner: ${winner}`
  }
  else {
    status = `Next player: ${xIsNext ? "X" : "O"}`
  }

  return (
    <>
      <div className="status">{status}</div>
      <div className="board-row">
        <Square value={squareArr[0]} onSquareClick={() => handleClick(0)} />
        <Square value={squareArr[1]} onSquareClick={() => handleClick(1)} />
        <Square value={squareArr[2]} onSquareClick={() => handleClick(2)} />
      </div>
      <div className="board-row">
        <Square value={squareArr[3]} onSquareClick={() => handleClick(3)} />
        <Square value={squareArr[4]} onSquareClick={() => handleClick(4)} />
        <Square value={squareArr[5]} onSquareClick={() => handleClick(5)} />
      </div>
      <div className="board-row">
        <Square value={squareArr[6]} onSquareClick={() => handleClick(6)} />
        <Square value={squareArr[7]} onSquareClick={() => handleClick(7)} />
        <Square value={squareArr[8]} onSquareClick={() => handleClick(8)} />
      </div>
    </>
  )
}

function Game() {
  const [history, setHistory] = useState([Array(9).fill(null)]);
  const [curMove, setCurMove] = useState(0);
  const xIsNext = curMove % 2 === 0
  const curSquareArr = history[curMove]

  function handlePlay(nextSquareArr: SquareArr) {
    const nextHistory = [...history.slice(0, curMove + 1), nextSquareArr]
    setHistory(nextHistory)
    setCurMove(nextHistory.length - 1)
  }

  function jumpTo(nextMove: number) {
    setCurMove(nextMove)
  }

  // move是索引, moveRecord是移动记录组件
  const moveRecord = history.map((_squareArr: SquareArr, move) => {
    let description;

    if (move > 0) {
      description = 'Go to move #' + move;
    } else {
      description = 'Go to game start';
    }

    return (
      <li key={move}>
        <button onClick={() => jumpTo(move)}>{description}</button>
      </li>
    );
  })

  return (
    <div className="game">
      <div className="game-board">
        <Board xIsNext={xIsNext} squareArr={curSquareArr} onPlay={handlePlay} />
      </div>
      <div className="game-info">
        <ol>{moveRecord}</ol>
      </div>
    </div>
  )
}

export default Game

// cli4/src/views/jing-zi-qi/components/Game.vue
<script>
import Board from './Board.vue'
import { calculateWinner, calcNum } from './tool.js'

export default {
  name: 'Game', // 游戏
  components: {
    Board
  },
  data() {
    return {
      state: {
        history: [
          {
            squares: Array(9).fill(null),
            posi: [null, null],
          }
        ],
        stepNumber: 0,
        xIsNext: true,
      }
    };
  },
  computed: {
  },
  watch: {
  },
  created() {
  },
  mounted() {
  },
  methods: {
    jumpTo(step) {
      this.setState({
        stepNumber: step,
        xIsNext: (step % 2) === 0,
      })
    },
    handleClick(i) {
      const history = this.state.history.slice(0, this.state.stepNumber + 1)
        , current = history[history.length - 1]
        , squares = current.squares.slice()
        , posi = calcNum(i)

      if (calculateWinner(squares) || squares[i]) return;

      squares[i] = this.state.xIsNext ? 'X' : 'O'

      // 
      this.setState({
        history: history.concat(
          [
            {
              squares: squares,
              posi
            }
          ]
        ),
        stepNumber: history.length,
        xIsNext: !this.state.xIsNext
      })
    }
  },
  render() {
    const history = this.state.history
      , current = history[this.state.stepNumber]
      , winner = calculateWinner(current.squares)
      , moves = history.map((step, move) => {
        const desc = move
          ? `Go to move # ${move} (${step.posi[0]},${step.posi[1]})`
          : 'Go to game start'

        return (
          <li key={move}>
            <button
              onClick={() => this.jumpTo(move)}
            // class={{this.stepNumber === (history.length) ? 'active' : ''}}
            >{desc}</button>
          </li>
        )
      })

    const msg = 'Next player: ' + (this.state.xIsNext ? 'X' : 'O');
    let status = winner ? 'Winner: ' + winner : msg

    console.log(current.squares)

    return (
      <div class="game">
        <div class="game-board">
          <Board
            squares={current.squares}
            onClick={i => this.handleClick(i)}
          />
        </div>
        <div class="game-info">
          <div>{status}</div>
          <ol>{moves}</ol>
        </div>
      </div>
    )
  }
};
</script>

<style scoped lang="scss">
ol,
ul {
  padding-left: 30px;
}
.game {
  display: flex;
  flex-direction: row;
}

.game-info {
  margin-left: 20px;
}
.status {
  margin-bottom: 10px;
}
</style>
